connector:
    name: Test Connector
    jobs:
         test_custom_connector:
               title: custom_custom.jobs.test_custom_custom_connector.title
               type: export
               steps:
                    export:
                        title: custom_custom.jobs.test_custom_custom_connector.title                   
                        services:
                            reader: custom_custom.reader.file.custom
                            processor: pim_base_connector.processor.product_to_flat_array
                            writer:    pim_connector.writer.file.csv_product
                        