parameters:
#    custom_custom.example.class: Custom\CustomBundle\Example

services:
#    custom_custom.example:
#        class: %custom_custom.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
